### ISSUE TITLE
self update not working

### ISSUE THREAD

**Issue by shelane** [acquia/blt-launcher#4]
Run `blt self-update`

Result:
```
You must run this command from within a BLT-generated project.
```

Go to a BLT project and run `blt self-update`

Result:
```
  Command "self-update" is not defined. 
```

**Comment by UTCGilligan** [comment]
```
╰─ which blt                                                                                               10034  17:51:34 
blt () {
	if [[ ! -z ${AH_SITE_ENVIRONMENT} ]]
	then
		PROJECT_ROOT="/var/www/html/${AH_SITE_GROUP}.${AH_SITE_ENVIRONMENT}"
	elif [ "`git rev-parse --show-cdup 2> /dev/null`" != "" ]
	then
		PROJECT_ROOT=$(git rev-parse --show-cdup)
	else
		PROJECT_ROOT="."
	fi
	if [ -f "$PROJECT_ROOT/vendor/bin/blt" ]
	then
		$PROJECT_ROOT/vendor/bin/blt "$@"
	elif [ -f "./vendor/bin/blt" ]
	then
		./vendor/bin/blt "$@"
	else
		echo "You must run this command from within a BLT-generated project."
		return 1
	fi
}
```

**Comment by danepowell** [comment]
You'll need to remove the existing BLT alias from `.bash_profile`, `.profile`, or wherever it's defined on your system.

**Comment by shelane** [comment]
After removing the function that was in my `.bash_profile` I run this:
```
which blt
/usr/local/bin/blt

blt self-update
BLT Launcher Version: v1.0.2
PHP Fatal error:  Uncaught Humbug\SelfUpdate\Exception\FilesystemException: The current phar file is not writeable and cannot be replaced: /usr/local/bin/blt. in phar:///usr/local/bin/blt/vendor/padraic/phar-updater/src/Updater.php:438
Stack trace:
#0 phar:///usr/local/bin/blt/vendor/padraic/phar-updater/src/Updater.php(101): Humbug\SelfUpdate\Updater->setLocalPharFile('/usr/local/bin/...')
#1 phar:///usr/local/bin/blt/bin/blt.php(93): Humbug\SelfUpdate\Updater->__construct(NULL, false)
#2 /usr/local/bin/blt(14): require('phar:///usr/loc...')
#3 {main}
  thrown in phar:///usr/local/bin/blt/vendor/padraic/phar-updater/src/Updater.php on line 438
```

**Comment by danepowell** [comment]
`sudo blt self-update`
